name: Cedrus's Site
url: "https://cedrus.neocities.org"

source: src
destination: public

gems:
    - jekyll-truthyfalsy
    - jekyll-paginate-v2

pagination:
    enabled: true
    per_page: 3
    permalink: "/page:num/"
    title: " Cedrus's Site - Blog - page :num"
    limit: 0
    sort_field: "date"
    sort_reverse: true

pages: ./_pages
defaults:
    - scope:
          path: ""
      values:
          layout: "global"
